// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKjM4QydvErOBLopr0r9J5YrMumdvdXzk',
    appId: '1:1003847362218:web:9d5213d13a20a5da8552d3',
    messagingSenderId: '1003847362218',
    projectId: 'reddit-66776',
    authDomain: 'reddit-66776.firebaseapp.com',
    storageBucket: 'reddit-66776.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvVcC5QjY0Vd5wMS8d_tT3ddRc4M_G7zg',
    appId: '1:1003847362218:android:1c1cc33e25a428f48552d3',
    messagingSenderId: '1003847362218',
    projectId: 'reddit-66776',
    storageBucket: 'reddit-66776.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIdaR1D3aDvh9DyZpEOtqvMyTmxee70bc',
    appId: '1:1003847362218:ios:5d96e2fbddfb85948552d3',
    messagingSenderId: '1003847362218',
    projectId: 'reddit-66776',
    storageBucket: 'reddit-66776.appspot.com',
    iosClientId: '1003847362218-nn9bgp91lri095kuhq6bal74c0qq5fqn.apps.googleusercontent.com',
    iosBundleId: 'com.example.reddit',
  );
}
